### ISSUE TITLE
[Issue] Profile Page + Store is not themed.

### ISSUE THREAD

**Issue by EndlessPeanut** [SleepDaemon/Modern-Steam#1]
Hi,

Thanks for the fork, followed the install instructions correctly, and everything is skinned akin to the pictures (library, download page, pop out friends list, in-game overlay), except for my profile tab (activity, profile, friends, etc) + the steam store tab.

Have done multiple clean installs with purged caches from SFP everytime, so a bit stumped.

**Comment by SleepDaemon** [comment]
I'm aware of this, haven't really gotten around fixing it. I've been busy lately and I will be traveling soon to where the internet is limited. I don't think it's SFP's fault, I think one of the CSS files are wrong or missing. Feel free to figure it out yourself, my suggestion would be try older versions, and see in which version these issues don't exist in.

**Comment by SleepDaemon** [comment]
I found this neat skin if you want to check out.
https://github.com/Snudgee/Pure

**Comment by EndlessPeanut** [comment]
> I'm aware of this, haven't really gotten around fixing it. I've been busy lately and I will be traveling soon to where the internet is limited. I don't think it's SFP's fault, I think one of the CSS files are wrong or missing. Feel free to figure it out yourself, my suggestion would be try older versions, and see in which version these issues don't exist in.

No worries at all, thanks for the prompt reply. I'll try having a poke around with the CSS and see what sticks. I'll check out the Pure skin too, thanks again.

**Comment by SleepDaemon** [comment]
> > I'm aware of this, haven't really gotten around fixing it. I've been busy lately and I will be traveling soon to where the internet is limited. I don't think it's SFP's fault, I think one of the CSS files are wrong or missing. Feel free to figure it out yourself, my suggestion would be try older versions, and see in which version these issues don't exist in.
> 
> No worries at all, thanks for the prompt reply. I'll try having a poke around with the CSS and see what sticks. I'll check out the Pure skin too, thanks again.

Have you find fix? cause i havent.

**Comment by SleepDaemon** [comment]
> This problem occurs because the CSS in the skin folder is not replaced,this can solve it https://github.com/AikoMidori/steam-dark-mode

I'll test this later

**Comment by SleepDaemon** [comment]
This fixed the issue, thanks @PIut02
