### ISSUE TITLE
Steam has been updated

### ISSUE THREAD

**Issue by Fan4eGGG** [SleepDaemon/Modern-Steam#11]
I don't know if I'm writing here and in general I don't know who to turn to, but after yesterday's Steam update the drop-down menus became default and look like [this ](https://prnt.sc/oX2xkuLvbhzt ), [this ](https://prnt.sc/AHuFqiBiHZBq), [this](https://prnt.sc/ii-GsUVw7gT9) etc.
is it possible to fix it somehow? if not, where to turn for help?
thanks.

**Comment by SleepDaemon** [comment]
Hey, I sadly no longer maintain this repo. I recommend you check out https://steambrew.app/, they have metro skin that is upto date.
